//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR28
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD_DES
    {
        public FOOD_DES()
        {
            this.NUT_DATA = new HashSet<NUT_DATA>();
        }
    
        public int NDB_No { get; set; }
        public short FdGrp_Cd { get; set; }
        public string Long_Desc { get; set; }
    
        public virtual FD_GROUP FD_GROUP { get; set; }
        public virtual ICollection<NUT_DATA> NUT_DATA { get; set; }
    }
}
