//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR28
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUT_DATA
    {
        public int NDB_No { get; set; }
        public short Nutr_No { get; set; }
        public Nullable<float> Nutr_Val { get; set; }
    
        public virtual FOOD_DES FOOD_DES { get; set; }
        public virtual NUTR_DEF NUTR_DEF { get; set; }
    }
}
