//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR28
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUTR_DEF
    {
        public NUTR_DEF()
        {
            this.NUT_DATA = new HashSet<NUT_DATA>();
        }
    
        public short Nutr_No { get; set; }
        public string Units { get; set; }
        public string Tagname { get; set; }
        public string NutrDesc { get; set; }
        public short Num_Dec { get; set; }
    
        public virtual ICollection<NUT_DATA> NUT_DATA { get; set; }
    }
}
